version: '3'

services:
  harvest:
    image: makotow/harvest-docker:1.1-harvest1.4.2
    volumes:
      - ${PWD}/harvest/netapp-harvest.conf:/opt/netapp-harvest/netapp-harvest.conf
    restart: always
  graphite:
    image: hopsoft/graphite-statsd
    ports:
      - "80:80"
      - "81:81"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    environment:
      GF_SERVER_ROOT_URL: "xxxxxxxxxxxxx"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    volumes:
      - ${PWD}/graphite/configs:/opt/graphite/conf
      - ${PWD}/graphite/data:/opt/graphite/storage
      - ${PWD}/statsd:/opt/statsd
    restart: always
# volumes:
#   netapp-harvest-vol:
#   graphite-vol:
